all:
	g++ client.cpp -o client -ltorrent-rasterbar -lboost_filesystem -lboost_system -std=c++0x
	g++ magnet_uri.cpp -o uri -ltorrent-rasterbar -lboost_filesystem -lboost_system -std=c++0x
	g++ info.cpp -o info -ltorrent-rasterbar -lboost_filesystem -lboost_system -std=c++0x
